# Configure main menu and social menu
# [[main]]
# identifier = "home"
# name = "主页"
# url = "/"
# [main.params]
# icon = "home"
# newtab = false

# [[social]]
# identifier = "github"
# name = "GitHub"
# url = "https://github.com/flowerinsnowdh"

# [social.params]
# icon = "brand-github"

# [[social]]
# identifier = "bilibili"
# name = "哔哩哔哩"
# url = "https://space.bilibili.com/295230912"

# [social.params]
# icon = "brand-bilibili"
