name: 'Test & Artifact'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup hugo
        run: curl -sL https://github.com/gohugoio/hugo/releases/download/v0.147.0/hugo_extended_0.147.0_linux-amd64.tar.gz | tar -zx -C ../

      - name: Build with hugo
        run: ../hugo

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: public/*
